"""rename department

Revision ID: 510572a67643
Revises: ac7d26430f2a
Create Date: 2024-10-03 11:19:06.288585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510572a67643'
down_revision = 'ac7d26430f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
